name: Check Prettier Formatting

on:
  pull_request:
    branches:
      - main

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Check formatting
        run: npm run format:check
        continue-on-error: true  # Continue to set status even if formatting check fails

      - name: Set status
        if: ${{ failure() }}  # Only set status if previous step failed (i.e., formatting check failed)
        uses: actions/github-script@v4
        with:
          script: |
            github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: github.sha,
              state: 'failure',
              context: 'Prettier Formatting Check',
              description: 'Code formatting check with Prettier failed. Please fix the formatting issues.',
            })
          github-token: ${{ secrets.GITHUB_TOKEN }}
